services:
  fluent-bit:
    build:
      context: fluent-bit-emf
    mem_limit: 70m
    cpu_count: 256
    ports:
      - "5170:5170"
    volumes:
      - ./output:/tmp/emf_test
    environment:
      - FLUENT_BIT_PLUGIN_DIR=/fluent-bit/plugins
  emf-generator:
    build: test-bed
    environment:
      - FLUENT_HOST=fluent-bit
      - PORT=5170
      - RPS=16000
      - RETRIES=30
      - RETRY_INTERVAL=2s

volumes:
  output:
