services:
  fluent-bit:
    build:
      dockerfile: Dockerfile.fluent-bit
    mem_limit: 512m
    cpu_count: 256
    ports:
      - "5170:5170"
    volumes:
      - ./output:/tmp/emf_test
    environment:
      # these are fake credentials simply to force aws-sdk to generate a valid header for testing
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_DEFAULT_REGION=us-west-2
      - FLUENT_BIT_PLUGIN_DIR=/fluent-bit/plugins
  emf-generator:
    build: test-bed
    environment:
      - HOST=fluent-bit
      - PORT=5170
      - RPS=15000
  mock-cloudwatch-server:
    build: mock-cloudwatch-server
    ports:
      - "5173:5173"
    environment:
      - PORT=5173

volumes:
  output:
