services:
  fluent-bit:
    build:
      dockerfile: Dockerfile.fluent-bit
    mem_limit: 70m
    cpu_count: 256
    ports:
      - "5170:5170"
    volumes:
      - ./output:/tmp/emf_test
    environment:
      - FLUENT_BIT_PLUGIN_DIR=/fluent-bit/plugins
  emf-generator:
    build: test-bed
    environment:
      - FLUENT_HOST=fluent-bit
      - PORT=5170
      - RPS=16000
      - RETRIES=30
      - RETRY_INTERVAL=2s
  mock-cloudwatch-server:
    build: mock-cloudwatch-server
    ports:
      - "5173:5173"
    environment:
      - PORT=5173

volumes:
  output:
