name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fluent-bit-emf
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache-dependency-path: fluent-bit-emf/go.sum
          go-version-file: fluent-bit-emf/go.mod
      - name: Build
        run: go build
      - name: Test
        run: go test
